environment: pro
server:
  port: 80
spring:
  datasource:
    username: root
    password: 12345678
  redis:
    port: 6379
    password:
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
