environment: dev
server:
  port: 8080
spring:
  datasource:
    username: root
    password: 12345678
# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
