auth: hanyun
spring:
  profiles:
    active: @profileActive@
  thymeleaf:
    check-template-location: true
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/
    cache: false

mybatis:
  type-aliases-package: com.hanyun.lee.entity
  mapper-locations: classpath:mapping/*.xml
