environment: dev
server:
  port: 8080
spring:
  datasource:
    username: root
    password: 12345678
#    schema: classpath:db/schema-mysql.sql
#    data: classpath:db/data-mysql.sql
  redis:
    port: 6379
    password:
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



twins:
  cas-server-url-prefix:  http://testld.ldforms.com:88/cas
  cas-login-url: http://testld.ldforms.com:88/cas/login
  cas-logout-url: http://testld.ldforms.com:88/cas/logout
  shiro-server-url-prefix: http://localhost:8080
  case-filter-url-patter: /cas
  login-url:  http://testld.ldforms.com:88/cas/login?service=http://localhost:8080/cas
